### PR TITLE
remove 7.10 testing from CI script

### LINKED ISSUE #2: No install-plan with GHC-7.10.3
https://travis-ci.org/haskell-servant/servant-nix/jobs/391933328

### PR DESCRIPTION
**Pull request by alpmestan**
Fixes #2.

### CODE REVIEW

**Comment by phadej** [comment]
This doesn't remove

```
tested-with:
  GHC==7.10.3,
```

I'd like that `.travis.yml` would be always (if possible) generated with `haskell-ci`.

**Comment by phadej** [comment]
Also if we don't test with `servant-0.13`, lower bound have to be increased too (and new release made therefore).

**Comment by alpmestan** [comment]
Right, I need to install haskell-ci and learn properly how to use it. Only tried it once.

**Comment by phadej** [comment]
I ths fixed in #1

**Pull request closed without merging**
